### ISSUE TITLE
objective function

### ISSUE THREAD

**Issue by Yuanpengli** [aspuru-guzik-group/phoenics#2]
Hi  Florian Hase,

I have read this paper.  You have been mention many objective function in the Supplementary Information, such as Dejong, Camel, Branin.  I could not find objective function in the code. 
Could you tell me how can I find it. Many thanks!!

Best wishes

**Comment by FlorianHase** [comment]
Hi @Yuanpengli, 
thank you for your message. Indeed, some of the benchmark functions which are reported in the paper have not made it to the repository, for which I would like to apologize. I just uploaded python implementations of all 15 benchmark functions. You can find them in `benchmark_functions.py` in `examples`. Please let me know if this answers your question, and if the file lists all the functions you were looking for.

**Comment by Yuanpengli** [comment]
Thank you. It is very useful.
